### ISSUE TITLE
define array of grades.

### ISSUE THREAD

**Issue by tomi-casabona** [tomi-casabona/climbify#37]
now, getMaxCompletedGrade function works with numbers, but the real data must be variable

**Comment by opujade** [comment]
grados_de_escalada = [
    {
        "escala": "YDS (USA)",
        "grados": ["5.5", "5.6", "5.7", "5.8", "5.9", "5.10a", "5.10b", "5.10c", "5.10d", "5.11a", "5.11b", "5.11c", "5.11d", "5.12a", "5.12b", "5.12c", "5.12d", "5.13a", "5.13b", "5.13c", "5.13d", "5.14a", "5.14b", "5.14c", "5.14d", "5.15a", "5.15b", "5.15c", "5.15d"]
    },
    {
        "escala": "UIAA (Europa)",
        "grados": ["IV", "IV+", "V", "V+", "VI", "VI+", "VII-", "VII", "VII+", "VIII-", "VIII", "VIII+", "IX-", "IX", "IX+", "X-", "X", "X+", "XI-", "XI", "XI+", "XII-", "XII", "XII+"]
    },
    {
        "escala": "French",
        "grados": ["5a", "5b", "5c", "6a", "6a+", "6b", "6b+", "6c", "6c+", "7a", "7a+", "7b", "7b+", "7c", "7c+", "8a", "8a+", "8b", "8b+", "8c", "8c+", "9a", "9a+", "9b", "9b+", "9c"]
    },
    {
        "escala": "British (E)",
        "grados": ["E1 5a", "E2 5b", "E3 5c", "E4 6a", "E5 6b", "E6 6b", "E7 6c", "E8 6c", "E9 7a", "E10 7a", "E11 7b"]
    },
    {
        "escala": "AUS",
        "grados": ["10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35"]
    }
]
