### ISSUE TITLE
Convert app to native with Capacitor

### ISSUE THREAD

**Issue by opujade** [tomi-casabona/climbify#86]
To test the app with mobile devices or share it to Google Play and Apple Store we need to convert it with Capacitor

**Comment by tomi-casabona** [comment]
capacitor is the app that Luis told us about ?

**Comment by opujade** [comment]
Yes! As far as I know:
- Connector to convert the React App to a native app.
- Android Studio/Xcode to compile and test the app in mobile devices.
- Google Play Console/App Store Connect to distribute the app.
